"""fixed the follows table

Revision ID: 1e74cbd76c6d
Revises: 9951361199d7
Create Date: 2023-02-14 22:41:22.751595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e74cbd76c6d'
down_revision = '9951361199d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], name=op.f('fk_followers_followed_id_users')),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], name=op.f('fk_followers_follower_id_users'))
    )
    op.drop_table('follows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('following_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], name='fk_follows_following_id_users'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_follows_user_id_users'),
    sa.PrimaryKeyConstraint('user_id', 'following_id', name='pk_follows')
    )
    op.drop_table('followers')
    # ### end Alembic commands ###
