"""updated the db to include comments aswell

Revision ID: 793620dce934
Revises: d5d998845d97
Create Date: 2023-02-06 22:11:43.392548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '793620dce934'
down_revision = 'd5d998845d97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'comment', ['comment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('comment_id')

    # ### end Alembic commands ###
